Added drop records table migration
department-of-veterans-affairs/caseflow-efolder pull request #1279
Opened 2020-12-29 17:35 UTC by sahalliburton

### Description
Added rails migration to remove the `records` table as it has been renamed to `records2020`

See [this document](https://hackmd.io/KOW31Pi1SGWZarqMsh2nfA?view#Resolution) for further details

2021-01-05 18:23 UTC, aroltsch requested changes
I think you'd also need to run db:migrate locally to update schema.rb

2021-01-05 18:28 UTC, sahalliburton commented
> I think you'd also need to run db:migrate locally to update schema.rb

Apologies, it did not commit the first time evidently. I have just pushed the update, thanks for catching that!

2021-01-05 20:27 UTC, alisan16 approved these changes
LGTM, please figure out the failure in the rake task before merging

2021-01-11 19:39 UTC, sahalliburton commented on Gemfile
> +gem "bgs", git: "https://github.com/department-of-veterans-affairs/ruby-bgs.git", ref: "7d7c67f7bad5e5aa03e257f0d8e57a4aa1a6cbbf"
Updated per instructions form [this slack thread](https://dsva.slack.com/archives/C2ZAMLK88/p1609807626159400)

2021-01-11 19:40 UTC, sahalliburton commented on .security.yml
> +  CVE-2015-9284: 2021-06-30
Moved the audit date out another 6 months as there is still no patch and removed an old security audit that seems to have been resolved

2021-01-11 20:27 UTC, aroltsch approved these changes
LGTM

2021-01-12 17:11 UTC, merged