Mattray gov/appeals 10276
department-of-veterans-affairs/caseflow-efolder pull request #1334
Opened 2022-12-16 01:52 UTC by mikefinneran

Resolves APPEALS-10276

### Description
Updated manifest fetcher to fetch the documents that have changed since the last time the manifest was fetched. The manifest fetcher's documents method will return the result of either the fetch_documents method or the fetch_delta_documents method based on whether or not the manifest's source is current. If the source is not current it will use the original fetch_documents to get all the documents and delete and recreate all the Record models for the documents. If the manifest source is current it will use a new fetch_delta_documents method in the VBMS service. This method takes in the manifest sources's fetched_at field and builds a VBMS request for document version references within a certain date range. It then sends and logs the request and returns the documents that have changed. The document creator will then delete the old versions of the updated documents and replace them with updated ones.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
Make sure the docker containers are running ```make up```
Run all the tests ```make test```
Run just the Manifest Fetcher tests ```bundle exec rspec spec/services/manifest_fetcher_spec.rb ```
Run just the Document Creator tests ```bundle exec rspec spec/services/document_creator_spec.rb```

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2022-12-16 01:54 UTC, mikefinneran commented on docker-compose.yml
> +    image: redis:3.2.10
Is this a M1 or local system specific change and do we want this in prod?

2022-12-16 01:54 UTC, mikefinneran commented on .ruby-version
> +2.7.3
Is this a M1 or local system specific change and do we want this in prod?

2022-12-16 13:56 UTC, jshields13 commented on .ruby-version
> +2.7.3
@mikefinneran Yeah I would be hesitant to just randomly update the ruby version. That should have its own story with proper testing

2022-12-16 13:56 UTC, jshields13 commented on app/jobs/v2/download_manifest_job.rb
> +  end
Not a filing comment but we should be adding tomdoc style comments to new methods

2022-12-16 13:56 UTC, jshields13 commented on app/services/document_creator.rb
> +  end
Could factor out this into a concern so you don't have to define it in every file

2022-12-16 13:56 UTC, jshields13 commented on app/services/external_api/vbms_service.rb
> +
This method shoudl really have proper comments following the tom doc style guide

2022-12-16 13:56 UTC, jshields13 commented on app/services/manifest_fetcher.rb
> +  end
Method comments be useful

2022-12-16 13:56 UTC, jshields13 commented on app/services/manifest_fetcher.rb
> +  end
Looks like this is also repeated across some files. I would consider moving into a concern. May of been worth making a reporting concern or utility. This will make maintaining code a nightmare if we want to change or add to our logging

2022-12-16 13:57 UTC, jshields13 requested changes
Test plans need to be jira and linked to the PR description

2022-12-16 21:44 UTC, mattray-gov approved these changes
LGTM

2022-12-20 20:37 UTC, zurbergram approved these changes

2022-12-20 21:35 UTC, maura-shaughnessy-bah submitted a review, later dismissed

2022-12-20 23:28 UTC, mgrozinski approved these changes
lgtm

2022-12-20 23:31 UTC, merged