APPEALS-26715 added deprecation warning and spec tests from caseflow
department-of-veterans-affairs/caseflow-efolder pull request #1402
Opened 2023-08-02 20:16 UTC by AKeyframe

Resolves #{efolder issue number} / department-of-veterans-affairs/caseflow#{caseflow issue number} / CASEFLOW-{JIRA number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Add your indexes safely (see [Caseflow::Migrations](https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/caseflow/migration.rb)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2023-08-03 18:23 UTC, jcroteau reviewed
🤩 Looking good! There are a few cosmetic changes that I've recommended in the diff.

Also, a few more overall suggestions:
- [ ] The PR title should have format `devname/APPEALS-XXXX <story title>`. 
    - So in this case, something like `akagebein/APPEALS-26715 Setup monitoring for deprecation warnings` would do.
- [ ] I think it would be good to finish filling out the template in the PR description. 
- [ ] A Jira Test issue (Xray test) is required on all new code (per our contract)
  - [ ] In preparation for that, it would be good if you were to write out the manual steps for your test plan under the **Testing Plan** section. 
    - For this, a simple test of accessing the Rails console, executing `ActiveSupport::Deprecation.warn("test deprecation warning")`, and checking that Sentry and the `#appeals-deprecation-alerts` Slack channel received messages should be sufficient.
  - [ ] I can work with you on creating a Jira Test story if you haven't done this before.

Once you've done the above and moved the PR into `Ready for Review`, I'll approve and we can move on to UAT...

2023-08-03 20:46 UTC, jcroteau approved these changes
🎈

2023-08-04 19:09 UTC, jcroteau requested changes
There is one small improvement we can make to the Slack alert titles...

2023-08-04 19:09 UTC, jcroteau commented on config/initializers/deprecation_warning_subscriber.rb
> +      .send_notification(event.payload[:message], SLACK_ALERT_TITLE, SLACK_ALERT_CHANNEL)
From our recent UAT testing of https://github.com/department-of-veterans-affairs/caseflow/pull/19078, we found that the alerts look like this in [DSVA `#appeals-deprecation-alerts`](https://dsva.slack.com/archives/C05L7AMMV62):


<img width="632" alt="image" src="https://github.com/department-of-veterans-affairs/caseflow/assets/3683255/8dd9249d-8a40-44b1-83a8-871516b06262">

It's not immediately obvious which environment they are coming from.

Let's add some more detail to the Slack alert title, maybe so that it reads like

```
Deprecation Warning - efolder (uat)
```

```suggestion
    slack_alert_title = "Deprecation Warning - #{APP_NAME} (#{ENV['DEPLOY_ENV']})"
    
    SlackService
      .new(url: ENV["SLACK_DISPATCH_ALERT_URL"])
      .send_notification(event.payload[:message], slack_alert_title, SLACK_ALERT_CHANNEL)
```

2023-08-04 19:09 UTC, jcroteau commented on config/initializers/deprecation_warning_subscriber.rb
> +  SLACK_ALERT_TITLE = "Deprecation Warning"
```suggestion
  APP_NAME = "efolder"
```

2023-08-04 20:15 UTC, jcroteau commented
📝 I wrote up a story for the System Team to add that `SSL_CERT_FILE` env var needed by the `SlackService`.

- [BPS-27264 - Appeals - Set env var 'SSL_CERT_FILE' for efolder](https://jira.devops.va.gov/browse/BPS-27264)

If they say it's going to take a long time for them to resolve that, we might just want to omit the Slack alerting logic from this PR. We can just use Sentry in the meantime for tracking eFolder deprecations. And then when they finish the work, we can add the Slack alerts back in.

2023-08-07 15:16 UTC, jcroteau submitted a review, later dismissed
⭐

2023-08-08 00:57 UTC, jcroteau submitted a review, later dismissed

2023-08-08 18:51 UTC, jcroteau commented
### UAT Results
This was tested successfully in UAT.
See resultant Sentry event at https://sentry.uat.appeals.va.gov/sentry/efolder-uat/issues/4297

2023-08-10 07:05 UTC, jcroteau approved these changes

2023-08-15 15:09 UTC, jcroteau approved these changes

2023-08-15 15:12 UTC, sbashamoni approved these changes

2023-08-15 18:51 UTC, merged