Alec k/appeals 28929
department-of-veterans-affairs/caseflow-efolder pull request #1441
Opened 2023-09-25 21:25 UTC by AKeyframe

Resolves #{efolder issue number} / department-of-veterans-affairs/caseflow#{caseflow issue number} / CASEFLOW-{JIRA number}

### Description
Please explain the changes you made here.

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Go to ...

- [ ] For higher-risk changes: [Deploy the custom branch to UAT to test](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Applications---Deploy-Custom-Branch-to-UAT)

### User Facing Changes
 - [ ] Screenshots of UI changes added to PR & Original Issue

 BEFORE|AFTER
 ---|---

### Code Documentation Updates
- [ ] Add or update code comments at the top of the class, module, and/or component.

### Database Changes
*Only for Schema Changes*

* [ ] Timestamps (created_at, updated_at) for new tables
* [ ] Column comments updated
* [ ] Verify that `migrate:rollback` works as desired ([`change` supported functions](https://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method))
* [ ] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [ ] Appropriate indexes added (especially for foreign keys, polymorphic columns, unique constraints, and Rails scopes)
* [ ] Add your indexes safely (see [Caseflow::Migrations](https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/caseflow/migration.rb)
* [ ] DB schema docs updated with `make docs` (after running `make migrate`)
* [ ] #appeals-schema notified with summary and link to this PR
* [ ] Any non-obvious semantics or logic useful for interpreting database data is documented at [Caseflow Data Model and Dictionary](https://github.com/department-of-veterans-affairs/caseflow/wiki/Caseflow-Data-Model-and-Dictionary)

### Integrations: Adding endpoints for external APIs
* [ ] Check that Caseflow's external API code for the endpoint matches the code in the relevant integration repo
  * [ ] Request: Service name, method name, input field names
  * [ ] Response: Check expected data structure
* [ ] Update Fakes
* [ ] Integrations impacting functionality are tested in Caseflow UAT

2023-09-29 23:53 UTC, jcroteau reviewed
Really great work on this so far!

- [x] I made a few minor requests (See comments on diff).
- [x] I also need to come back and revisit the 6.1 default overrides in `config/application.rb` before I approve.

2023-09-29 23:53 UTC, jcroteau commented on Gemfile
> +gem "pg", "~> 1.1", platforms: :ruby
I'm guessing this this `pg` update was prompted by the following error when you ran `bin/rails app:update`?

```
rails aborted!
LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? can't activate pg (~> 1.1), already activated pg-0.21.0. Make sure all dependencies are added to Gemfile.

Caused by:
Gem::LoadError: can't activate pg (~> 1.1), already activated pg-0.21.0. Make sure all dependencies are added to Gemfile.

Tasks: TOP => railties:install:migrations => db:load_config
```

After much Googling and toying around, I could not find a satisfactory solution that didn't mean upgrading `pg`.

I didn't see any breaking changes in the [`pg` changelog](https://github.com/ged/ruby-pg/blob/master/History.md) on the way to `v1.5.4`, however, I'm wondering if we shouldn't keep this pinned at `1.1.Z` out of caution? 🤔 

```suggestion
gem "pg", "~> 1.1.0", platforms: :ruby
```

**Note:** You'll have to `bundle update pg` to update the `Gemfile.lock` as well.

2023-09-29 23:53 UTC, jcroteau commented on app/assets/stylesheets/_commons.scss
> -
👍

2023-09-29 23:53 UTC, jcroteau commented on app/assets/stylesheets/_commons.scss
> -@import 'neat';
👋 "buh-bye"

2023-09-29 23:53 UTC, jcroteau commented on config/application.rb
> +
📝 **Note to self:** I'll need to come back and look at this again after I've had a change to review the new settings in `new_framework_defaults_6_1.rb`...

2023-09-29 23:53 UTC, jcroteau commented on config/cable.yml
> +  channel_prefix: caseflow_efolder_production
Looks like the newline got accidentally removed here:

```suggestion
  channel_prefix: caseflow_efolder_production

```

2023-09-29 23:53 UTC, jcroteau commented on config/environments/development.rb
> +  # See this commit for why we aren't including them. https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/1030/commits/3d8e1061dc8b9e7dca8cb658f3af3a301a070df0
❤️ Thanks for remember to add in this contextual comment!

I might reword it a little bit (and leave out the line references, since those change easily):

```suggestion
  # Fall back to the `application.rb` setting for `config.cache_store`, which properly uses the Redis instance we have running in a Docker container.
  # See this commit for historical context: https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/1030/commits/3d8e1061dc8b9e7dca8cb658f3af3a301a070df0
```

2023-09-29 23:53 UTC, jcroteau commented on config/environments/production.rb
>    # config.assets.css_compressor = :sass
Since we're also compressing JS, what do you say we either keep the original comment here, or split the lines out like so?

```suggestion  
  # Compress JavaScript using a preprocessor.
  config.assets.js_compressor = :uglifier
  
  # Compress CSS using a preprocessor.
  # config.assets.css_compressor = :sass
```

2023-09-29 23:53 UTC, jcroteau commented on config/initializers/assets.rb
> +Rails.application.config.assets.precompile += %w( *.woff *.woff2 *.eot *.ttf )
Looks like we're missing another newline here

```suggestion
Rails.application.config.assets.precompile += %w( *.woff *.woff2 *.eot *.ttf )

```

2023-09-29 23:53 UTC, jcroteau commented on config/initializers/bgs.rb
> +end
I'm pretty sure this deprecation warning is related to the upcoming Zeitwork migration in Rails 7.0.

Unless I'm mistaken, we don't have to address this warning as part of the 6.1 upgrade. So we can probably leave this file unchanged.

2023-09-29 23:53 UTC, jcroteau commented on config/initializers/filter_parameter_logging.rb
> +#Rails.application.config.filter_parameters += [:password]
👍 I think this should be fine.

You can clean up this comment.

```suggestion
Rails.application.config.filter_parameters += [
  :passw, :secret, :token, :_key, :crypt, :salt, :certificate, :otp, :ssn
]
```

2023-09-29 23:53 UTC, jcroteau commented on config/initializers/s3.rb
> +end
I'm pretty sure this deprecation warning is related to the upcoming Zeitwork migration in Rails 7.0.

Unless I'm mistaken, we don't have to address this warning as part of the 6.1 upgrade. So we can probably leave this file unchanged.

2023-09-29 23:53 UTC, jcroteau commented on config/initializers/vbms.rb
> +end
I'm pretty sure this deprecation warning is related to the upcoming Zeitwork migration in Rails 7.0.

Unless I'm mistaken, we don't have to address this warning as part of the 6.1 upgrade. So we can probably leave this file unchanged.

2023-09-29 23:53 UTC, jcroteau commented on config/initializers/vva.rb
> +end
I'm pretty sure this deprecation warning is related to the upcoming Zeitwork migration in Rails 7.0.

Unless I'm mistaken, we don't have to address this warning as part of the 6.1 upgrade. So we can probably leave this file unchanged.

2023-10-02 18:37 UTC, AKeyframe commented on Gemfile.lock
> +    d3-rails (7.8.5)
Since this is updating to caseflow-commons 1.0 and d3 is a dependency of caseflow-commons running bundle install it's going to update d3 to 7.8.5 regardless. Unless you'd rather I add that to 27013.

2023-10-02 21:12 UTC, jcroteau commented on Gemfile.lock
> +    d3-rails (7.8.5)
I understand that `d3-rails` is a dependency of `caseflow-commons`, and that it will update when we `bundle update caseflow`, but it doesn't **_have_** to be updated (there are no other dependencies with version constraints on `d3-rails` that would force us to update it).  

So, staying on the side of caution, I say we just omit this change from `Gemfile.lock`. It can be a future exercise to update this gem if/as needed.

2023-10-02 21:15 UTC, jcroteau commented on config/initializers/bgs.rb
> +end
I think it's just like any other deprecation warning. We will have to address these before we upgrade to Rails 7 (for Zeitwork), but I'm pretty sure we can ignore them for now.

2023-10-02 21:24 UTC, jcroteau requested changes

2023-10-02 21:24 UTC, jcroteau commented on Gemfile.lock
> +    caseflow (0.4.8)
🎗️ **Reminder:** We'll need to `bundle update caseflow` to update the `Gemfile.lock` after `caseflow-commons` `1.0.0` gets merged.

2023-10-02 21:24 UTC, jcroteau commented on Gemfile.lock
> +    pg (1.5.4)
Please `bundle update pg` to resolve this version back to `1.1.Z` (since we are now constraining `pg` to `~> 1.1.0` in the `Gemfile`. 

You might have to undo the change to this line in your local editor beforehand if it won't update.

2023-10-05 23:16 UTC, jcroteau reviewed
👍 Awesome job. Just one small change request left. 

I can approve this PR once we've merged `caseflow-commons 1.0.0` into `master` and updated the eFolder `Gemfile.lock` accordingly.

2024-09-23 20:03 UTC, closed without merging